- id: '1788453019543'
  alias: Basculer_interrupter_test_1_au_depart
  description: ''
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: input_boolean.toggle
    metadata: {}
    target:
      entity_id: input_boolean.interrupteur_virtuel_1
    data: {}
  mode: single
- id: '1788561874450'
  alias: Lumiere virtuelle suit potentiometre
  description: ''
  triggers:
  - trigger: state
    entity_id: sensor.salon_xiao_esp32c6_rouge_xiao_potentiometer_value
  conditions: []
  actions:
  - action: input_number.set_value
    metadata: {}
    target:
      entity_id: input_number.lampe_virtuelle
    data:
      value: '{{ trigger.to_state.state | float }}'
  mode: single
- id: '1788644818241'
  alias: Ex 13.2 - incrementer recapteur virtuel apres 2s activation capteur virutel
  description: ''
  triggers:
  - trigger: switch.turned_on
    target:
      entity_id: input_boolean.exercice_13_capteur_virtuel
    options:
      behavior: each
      for:
        hours: 0
        minutes: 0
        seconds: 2
  - trigger: button.pressed
    target:
      entity_id: input_button.exercice_13_2_activer_manuellement_automatisation
    options: {}
  conditions: []
  actions:
  - action: input_number.increment
    metadata: {}
    target:
      entity_id: input_number.exercice_13_recepteur_virtuel
    data: {}
  mode: single
- id: '1789064316933'
  alias: Incrément si temp au-dessus de 10 deg Celsius seulement
  description: ''
  triggers:
  - trigger: switch.turned_on
    target:
      entity_id: input_boolean.exercice_13_capteur_virtuel
    options:
      behavior: each
      for:
        hours: 0
        minutes: 0
        seconds: 2
  - trigger: button.pressed
    target:
      entity_id: input_button.exercice_13_2_activer_manuellement_automatisation
    options: {}
  conditions:
  - condition: temperature.is_value
    target:
      entity_id: sensor.openweathermap_temperature
    options:
      behavior: any
      for: 00:00:00
      threshold:
        type: above
        value:
          active_choice: number
          number: 10
          unit_of_measurement: °C
  actions:
  - action: input_number.increment
    metadata: {}
    target:
      entity_id: input_number.exercice_13_recepteur_virtuel
    data: {}
  mode: single
- id: '1789065847309'
  alias: Exercice 13.8 - regarder TV sur mouvement
  description: ''
  triggers:
  - trigger: switch.turned_on
    target:
      entity_id: input_boolean.exercice_13_8_capteur_virtuel_de_mouvement
    options:
      behavior: each
      for:
        hours: 0
        minutes: 0
        seconds: 2
  conditions:
  - condition: numeric_state
    entity_id: input_number.exercice_13_8_capteur_virtuel_de_luminosite
    below: 40
  actions:
  - action: script.turn_on
    metadata: {}
    target:
      entity_id: script.exercice_13_regarder_tv
    data: {}
  mode: single
- id: '1789410407509'
  alias: Exercice 14 - Efforts influencent résultats
  description: ''
  triggers:
  - trigger: state
    entity_id: input_number.exercice_14_efforts
  conditions: []
  actions:
  - action: input_text.set_value
    metadata: {}
    target:
      entity_id: input_text.exercice_14_resultats
    data:
      value: '{{ (states(''input_number.exercice_14_efforts'') | int * 10) }} %'
  mode: single
- id: '1789596811809'
  alias: Test envoi courriel
  description: ''
  triggers:
  - trigger: switch.turned_on
    target:
      entity_id: input_boolean.exercice_13_capteur_virtuel
    options:
      behavior: each
      for:
        hours: 0
        minutes: 0
        seconds: 1
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      message: ex13 capteur virtuel activé.  Veuillez rapporter le tout à votre maitre
      title: Alerte Home Assistant
    target:
      entity_id: notify.s_trottier_home_assistant_s_trottier
  mode: single
- id: examen_pere_noel_en_route
  alias: Examen - Père Noël en route
  description: Met à jour le message lorsque le Père Noël est en route le 24 décembre.
  triggers:
  - trigger: state
    entity_id: input_boolean.pere_noel_dans_ma_maison
  conditions:
  - condition: state
    entity_id: input_boolean.pere_noel_dans_ma_maison
    state: 'off'
  - condition: template
    value_template: '{% set date_examen = as_datetime(states(''input_datetime.date_examen''))
      %} {{ date_examen.month == 12 and date_examen.day == 24 }}'
  actions:
  - action: input_text.set_value
    target:
      entity_id: input_text.texte_examen
    data:
      value: Le Père Noël est en route!
  mode: single
- id: examen_pere_noel_arrive
  alias: Examen - Père Noël à la maison
  description: Avertit lorsque le Père Noël arrive et que je suis à la maison.
  triggers:
  - trigger: state
    entity_id: input_boolean.pere_noel_dans_ma_maison
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_boolean.je_suis_a_la_maison
    state: 'on'
  - condition: template
    value_template: '{% set date_examen = as_datetime(states(''input_datetime.date_examen''))
      %} {{ date_examen.month == 12 and date_examen.day == 24 }}'
  actions:
  - action: input_text.set_value
    target:
      entity_id: input_text.texte_examen
    data:
      value: Le Père Noël arrive, réveille-toi!
  mode: single
- id: examen_initialiser_date
  alias: Examen - Initialiser la date du jour
  description: Initialise la date virtuelle avec la date actuelle au démarrage.
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: input_datetime.set_datetime
    target:
      entity_id: input_datetime.date_examen
    data:
      date: '{{ now().strftime(''%Y-%m-%d'') }}'
  mode: single
- id: '1789754011220'
  alias: Xiao ESP32-C3 online status
  description: ''
  triggers:
  - trigger: state
    entity_id: binary_sensor.esphome_devices_xiao_esp32c3_bleu_online_status
  conditions: []
  actions:
  - action: logbook.log
    metadata: {}
    data:
      message: Changement état connection Xiao 32-C3 bleu
  mode: single
- id: '1789800000001'
  alias: Exercice 15.2 - Activer récepteur et envoyer courriel
  description: Agit sur le récepteur virtuel puis avise par courriel, avec une info
    de capteur obtenue via un modèle.
  triggers:
  - trigger: state
    entity_id: input_button.exercice_15_declencheur_manuel
  conditions: []
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.exercice_15_capteur_virtuel
    data: {}
  - action: notify.send_message
    metadata: {}
    data:
      title: Exercice 15 - Récepteur activé
      message: 'Le récepteur virtuel de l''exercice 15 vient d''être activé. Température
        extérieure actuelle : {{ states(''sensor.openweathermap_temperature'') }}
        °C.'
    target:
      entity_id: notify.s_trottier_home_assistant_s_trottier_locavora_org
  mode: single
- id: '1789800000002'
  alias: Exercice 15.3 - Courriel et écriture dans le journal système
  description: En plus d'envoyer un courriel, écrit la valeur du capteur dans le journal
    système (system_log) au niveau warning.
  triggers:
  - trigger: state
    entity_id: input_boolean.exercice_15_capteur_virtuel
    to: 'on'
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      title: Exercice 15.3 - Capteur activé
      message: 'Le capteur virtuel de l''exercice 15 est maintenant : {{ states(''input_boolean.exercice_15_capteur_virtuel'')
        }}.'
    target:
      entity_id: notify.s_trottier_home_assistant_s_trottier_locavora_org
  - action: system_log.write
    metadata: {}
    data:
      message: Capteur exercice 15 = {{ states('input_boolean.exercice_15_capteur_virtuel')
        }}
      level: warning
  mode: single
- id: '1789800000003'
  alias: Exercice 15.5 - Envoyer l'adresse IP de l'hôte au démarrage
  description: Retrouve l'adresse IP de l'hôte à l'aide d'un modèle et l'envoie par
    courriel au démarrage de Home Assistant.
  triggers:
  - trigger: homeassistant
    event: start
  conditions: []
  actions:
  - action: notify.send_message
    metadata: {}
    data:
      title: Home Assistant - Démarrage - Ex 15.5
      message: 'L''adresse IP de l''hôte Home Assistant est : {{ states(''sensor.local_ip'')
        }}'
    target:
      entity_id: notify.s_trottier_home_assistant_s_trottier_locavora_org
  mode: single
- id: '1789800000004'
  alias: Exercice 15.5 - Entrée journal quotidienne à 10h
  description: Ajoute une entrée dans le journal des activités à 10h tous les jours.
  triggers:
  - trigger: time
    at: '10:00:00'
  conditions: []
  actions:
  - action: logbook.log
    metadata: {}
    data:
      message: Entrée automatique quotidienne de l'exercice 15.5 à 10h.
  mode: single
- id: '1789800000005'
  alias: Exercice 15.6 - Action si capteur activé entre 10h et 12h
  description: N'effectue l'action que si le capteur virtuel est activé entre 10h
    et 12h inclusivement.
  triggers:
  - trigger: state
    entity_id: input_boolean.exercice_15_capteur_virtuel
    to: 'on'
  conditions:
  - condition: time
    after: '10:00:00'
    before: '12:00:01'
  actions:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.ex_13_7_lumiere_salon_virtuelle
    data: {}
  mode: single
- id: '1789800000006'
  alias: Exercice 15.7 - Action seulement le samedi et le dimanche
  description: Effectue une action seulement le samedi et le dimanche.
  triggers:
  - trigger: time
    at: 09:00:00
  conditions:
  - condition: time
    weekday:
    - sat
    - sun
  actions:
  - action: logbook.log
    metadata: {}
    data:
      message: Automatisation de fin de semaine exécutée (exercice 15).
  mode: single
- id: '1790023456758'
  alias: Exercice 16
  description: ''
  triggers:
  - trigger: zone.left
    target:
      entity_id: device_tracker.tracker_test2
    options:
      for: 00:00:00
      zone: zone.cegep
  conditions: []
  actions:
  - action: logbook.log
    metadata: {}
    data:
      message: '**** Zone quittee **** tracker 2'
      name: ABC
  - action: system_log.write
    metadata: {}
    data:
      level: error
      message: Ex16 - declenchee *****
  - action: notify.notify
    metadata: {}
    data:
      message: temp automatisatino corrigee!
  mode: single
- id: '1790029582240'
  alias: 'Exercice 16: Tracker Entered Cegep Zone'
  description: Triggers when tracker_test2 enters the Cegep zone
  triggers:
  - trigger: zone
    entity_id: device_tracker.tracker_test2
    zone: zone.cegep
    event: enter
  conditions: []
  actions:
  - action: notify.persistent_notification
    data:
      title: Zone Alert
      message: device_tracker.tracker_test2 entered Cégep!
  mode: single
- id: '1790030965852'
  alias: Exercice 16 - nouvelle syntaxe
  description: Triggers when tracker_test2 enters the Cegep zone
  triggers:
  - trigger: zone.left
    target:
      entity_id: device_tracker.tracker_test2
    options:
      zone: zone.cegep
  conditions: []
  actions:
  - action: notify.persistent_notification
    data:
      title: Zone Alert
      message: Exercice 16 - nouvelle syntaxe
  mode: single
- id: '1790130086097'
  alias: Pixel 6a au bureau
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - sensor.pixel6a_room
    to:
    - bureausousol
  conditions: []
  actions:
  - action: notify.notify
    metadata: {}
    data:
      message: pixel6a au bureau
  mode: single
