
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean:
  pere_noel_dans_ma_maison:
    name: Père Noël dans ma maison
    icon: mdi:string-lights
    initial: false

  je_suis_a_la_maison:
    name: Je suis à la maison

input_text:
  texte_examen:
    name: Texte examen
    max: 255

input_datetime:
  date_examen:
    name: Date examen
    has_date: true
    has_time: false
    initial: '2025-12-24'

lovelace:
  dashboards:
    noel-dashboard:
      mode: yaml
      title: Noël
      icon: mdi:string-lights
      show_in_sidebar: true
      filename: noel.yaml
