title: Exercice 15
views:
  - title: Exercice 15
    path: exercice-15
    icon: mdi:toggle-switch
    cards:
      - type: entities
        title: Capteur / Récepteur virtuel
        show_header_toggle: false
        entities:
          - entity: input_boolean.exercice_15_capteur_virtuel
            name: Capteur / Récepteur
          - entity: input_button.exercice_15_declencheur_manuel
            name: Déclencheur manuel
          - entity: sensor.local_ip
            name: Adresse IP de l'hôte
      - type: markdown
        title: Description des automatisations
        content: >-
          **15.2** - Active le récepteur virtuel et envoie un courriel contenant
          la température extérieure (modèle).


          **15.3** - Envoie un courriel et écrit la valeur du capteur dans le
          journal système (`system_log.write`, niveau warning).


          **15.4** - Au démarrage de Home Assistant, envoie l'adresse IP de
          l'hôte par courriel (obtenue via un modèle).


          **15.5** - Ajoute une entrée dans le journal des activités à 10h
          tous les jours.


          **15.6** - N'agit que si le capteur est activé entre 10h et 12h
          inclusivement.


          **15.7** - N'agit que le samedi et le dimanche.

      - type: logbook
        title: Journal des activités
        entities:
          - input_boolean.exercice_15_capteur_virtuel
