title: Noël
views:
  - title: Noël
    path: noel
    icon: mdi:string-lights
    cards:
      - type: entities
        title: Capteurs virtuels
        show_header_toggle: false
        entities:
          - entity: input_boolean.pere_noel_dans_ma_maison
            name: Père Noël dans ma maison
          - entity: input_boolean.je_suis_a_la_maison
            name: Je suis à la maison
          - entity: input_text.texte_examen
            name: Texte
          - entity: input_datetime.date_examen
            name: Date
      - type: horizontal-stack
        cards:
          - type: button
            name: Déplacer le Père Noël à la maison
            icon: mdi:home
            tap_action:
              action: call-service
              service: input_boolean.turn_on
              target:
                entity_id: input_boolean.pere_noel_dans_ma_maison
          - type: button
            name: Déplacer le Père Noël hors de la maison
            icon: mdi:home-export-outline
            tap_action:
              action: call-service
              service: input_boolean.turn_off
              target:
                entity_id: input_boolean.pere_noel_dans_ma_maison
      - type: markdown
        title: Père Noël est-il dans ma maison à la veille de Noël?
        content: >-
            {% set date_examen = as_datetime(states('input_datetime.date_examen')) %}
            {% if is_state('input_boolean.pere_noel_dans_ma_maison', 'off')
              and date_examen.month == 12 and date_examen.day == 24 %}
            Vrai
            {% else %}
            Faux
            {% endif %}
