exercice_13_regarder_tv:
  sequence:
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.ex_13_7_lumiere_salon_virtuelle
    data: {}
  - action: input_boolean.turn_on
    metadata: {}
    target:
      entity_id: input_boolean.exercice_13_tv_viruelle
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - action: input_boolean.turn_off
    metadata: {}
    target:
      entity_id: input_boolean.ex_13_7_lumiere_salon_virtuelle
    data: {}
  alias: Exercice 13  - regarder TV
  description: ''
